### ISSUE TITLE
Insecure flag not passed to rclone?

### ISSUE THREAD

**Issue by hydro-b** [clyso/chorus#12]
First of all: thanks for building and sharing this project with the rest of the world! I'm trying to use it on a freshly built k3s test "cluster" (single node), but run into some issues. I will create separate issues for each of those. This should make it easier for newbies (like me) to get chorus installed and working.

I'm using two Ceph S3 test clusters for "one" and "two", one being "main". Both of them are configured to use plain HTTP for now. So far I managed to get chorus to replicate the buckets for the users, but no data has been transferred. I have tested with a standalone rclone (my work station) to validate the working of both clusters, credentials, etc. That works. Checking the logs from the worker pods shows that although I have described to use `isSecure: false` for both storages. My hypotheses is that creating users / buckets is done by chorus itself, but that actual data transfer is done by rclone, and that the `isSecure: false` flag is not passed to rclone resulting in rclone using (the default?) port 443. If my hypotheses holds true this would be a bug.

Can you prove me wrong?

**Comment by arttor** [comment]
Hi @hydro-b, thank you for the interest in the project. I am very happy that we can test chorus installation steps on different environments and close gaps in our charts and docs. I'll attempt to replicate any issues on our test environment and will get back to you.

**Comment by arttor** [comment]
@hydro-b i think you are correct. Project e2e tests are passing with insecure config, because storage address in config contains schema. If address is passed to rclone with schema, then insecure flag is not required. 
I will create a fix. 
Is your storage config contains schema? If no can you please try with `http://`?

**Comment by hydro-b** [comment]
Thanks for the quick response!

> Is your storage config contains schema? If no can you please try with `http://`?

The storage config I used was not using `http://`, just the plain `ip-address`. I have changed that to use `http://ip-address-here` as well and now it works! \o/

Well, only after pointing it directly to the RGW daemons and not to the HAproxy (ingress) that is in front of it (must be some config issue there). That did give an interesting error message though (although not related to this issue):

```
{"level":"warn","app_id":"cojomn1f2chs73c6a0j0","app":"worker","task_type":"migrate:object:copy","task_id":"mgr:co:one:two:fliepje01:ceph_volume/__init__.py","task_queue":"migrate_obj_copy1","task_max_retry":25,"task_retried":7,"error":"SerializationError: failed to unmarshal error message\n\tstatus code: 503, request id: , host id: \ncaused by: UnmarshalError: failed to unmarshal error message\n\t00000000  3c 68 74 6d 6c 3e 3c 62  6f 64 79 3e 3c 68 31 3e  |<html><body><h1>|\n00000010  35 30 33 20 53 65 72 76  69 63 65 20 55 6e 61 76  |503 Service Unav|\n00000020  61 69 6c 61 62 6c 65 3c  2f 68 31 3e 0a 4e 6f 20  |ailable</h1>.No |\n00000030  73 65 72 76 65 72 20 69  73 20 61 76 61 69 6c 61  |server is availa|\n00000040  62 6c 65 20 74 6f 20 68  61 6e 64 6c 65 20 74 68  |ble to handle th|\n00000050  69 73 20 72 65 71 75 65  73 74 2e 0a 3c 2f 62 6f  |is request..</bo|\n00000060  64 79 3e 3c 2f 68 74 6d  6c 3e 0a                 |dy></html>.|\n\ncaused by: expected element type <Error> but have <html>","caller":"/build/service/worker/server.go:169","time":"2024-04-23T10:20:24Z","message":"process task failed. task will be retired"}
```
Is indeed "retired" meant here? Or is it a typo and should it read "retried"? Just checkin' ;-).

**Comment by arttor** [comment]
yes, retried 🤣
