### ISSUE TITLE
Run agent in kubernetes too?

### ISSUE THREAD

**Issue by hydro-b** [clyso/chorus#19]
Is it also possible to run the agent in kubernetes too? In the config example I did not find a reference to the image repository.

A standalone agent binary works, but it might be nice to have everything in k8s altogether.

**Comment by arttor** [comment]
agent image and chart will be added in #18 
I plan to merge it today and make release next week

**Comment by arttor** [comment]
Agent is added to Helm chart and available in [v0.5.3 release](https://github.com/clyso/chorus/releases/tag/v0.5.3).
