### ISSUE TITLE
Is the Grafana dashboard available anywhere?

### ISSUE THREAD

**Issue by PC-Admin** [clyso/chorus#39]
I keep seeing it mentioned, but is the Grafana dashboard for this tool publicly available?

**Comment by arttor** [comment]
Good question. We want to add grafana dashboard to marketplace but it is not done yet.
You can find exported dashboard json in [attached chorus-grafana.json](https://github.com/user-attachments/files/16438603/chorus-grafana.json). But to make it work you will probably have to fix datasource naming. It is currently using 2 datasources:
1. Prometheus datasource with id `prometheus`
2. Loki datasource with id `P8E80F9AEF21F6940`

If you don't need logs and already have prometheus datasource with `uid="prometheus"` it should work out of the box.

**Comment by PC-Admin** [comment]
Hi @arttor,

Thanks for sharing, I've been having a go at getting this working today but I've hit a road block.

From my grafana container (provided by cephadm) I can query the endpoint:
```
mcollins1@storage-13-09002:~/chorus$ sudo docker ps | grep grafana
c6f587338e34   quay.io/ceph/ceph-grafana:9.4.7           "/bin/sh -c 'grafana…"   41 minutes ago   Up 41 minutes
ceph-2b43dc80-4e31-11ef-9fb4-4920a8794200-grafana-storage-13-09002
mcollins1@storage-13-09002:~/chorus$ sudo docker exec -it c6f587338e34 /bin/bash
bash-4.4$ curl http://localhost:9090/metrics
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 4.9955e-05
go_gc_duration_seconds{quantile="0.25"} 5.804e-05
...
```

However, from the same location it seems only the metrics endpoint is available, while the Prometheus API is not.
```
bash-4.4$ curl http://localhost:9090/api/v1/status/buildinfo
404 page not found
bash-4.4$ curl http://localhost:9090/api/v1/label/__name__/values
404 page not found
bash-4.4$ curl 'http://localhost:9090/api/v1/query?query=up'
404 page not found
```

Here is how I've configured the endpoint in grafana (I gave it a custom uid which I've altered in the dashboard.json you gave me):
![grafana_debug_1](https://github.com/user-attachments/assets/b52eb7f4-9f0d-4091-8105-c54acf6808af)
![grafana_debug_2](https://github.com/user-attachments/assets/7d308b69-137c-49f1-b2c4-104384d03a29)

While trying to query the endpoint with a simple 'up' fails showing '404 page not found':
![grafana_debug_3](https://github.com/user-attachments/assets/11d98a01-7407-427b-ac97-e1c7c45c2e4d)

I don't suppose you know how I could establish a basic connectivity to prometheus here? That source is pointing to the prometheus endpoint of the chorus_agent container.

**Comment by arttor** [comment]
chorus expose metrics endpoint on `:9090/metrics` to prometheus. you should install prometheus somewhere in you environment and scrape metrics.

**Comment by PC-Admin** [comment]
Ahh of course, I was able to get it going, thank you for the assistance. I'll close this ticket as the original question was answered.
