### ISSUE TITLE
Add an optional flag to relax S3 bucket names check

### ISSUE THREAD

**Issue by mtse-btg** [clyso/chorus#42]
Hello Clyso team,

* Understanding that Amazon s3 spec no longer allows for the use of uppercase and underscore within S3 bucket names, and I appreciate your code currently have a regex check to enforce such naming convention.
  * https://github.com/clyso/chorus/blob/main/pkg/s3/validate.go#L27
* Our company has been using Ceph for many years (before the Amazon spec was updated), and we have some old buckets with underscore in their name.
  * In order for us to use Chorus to replicate currently, we need to compile our own copy of Chorus worker container by removing the underscore pattern from `validBucketName` in the Chorus source code.
* As a feature request, please may I ask if it would be possible to add a flag to `chorctl`, or to Worker YAML config, so that such option can be switched on for buckets with "relaxed" name to be replicated.
  * This would be similar to the config `rgw_relaxed_s3_bucket_names` which Ceph has introduced for its backward compatibility.

Many thanks.

**Comment by arttor** [comment]
@mtse-btg should be fixed. Can you please try with [v0.5.7 release](https://github.com/clyso/chorus/releases/tag/v0.5.7)?
